
import streamlit as st
import networkx as nx
import matplotlib.pyplot as plt
import random

# Full embedded distance matrix
distance_dict = {
  "Seif Eddine Mezned": {
    "Seif Eddine Mezned": 0.0,
    "Mehdi Bouthour": 9.17,
    "Mahdi Soudani": 7.19,
    "Mimouna Baya Chaaben": 2.82,
    "Mohamed Aziz Souissi": 28.18,
    "Ahmed Said Mohamed": 2.12,
    "Aymen El Hadhri": 20.17,
    "Mohamed Yamoun Hamdi": 7.19,
    "Abdelkarim Elhamdi": 7.19,
    "Mohamed Amine Zekri": 26.18,
    "El Fedi Zairi": 28.18,
    "Aya Hachana": 6.49,
    "Abidi Fares": 6.18,
    "Mohamed Aymen Hassini": 7.19,
    "Arij Aouina": 7.12,
    "Yasmine Jedidi": 0.2,
    "Yasmine Ben Ismail": 2.82,
    "Emna Barbouch": 0.19,
    "Khammassi Nour": 9.17,
    "Youssef Mohamed Bechir": 19.93,
    "Ben Abda Iskander": 8.18,
    "Yassine Ben Knani": 19.93,
    "Nabila Ben Zineb": 13.66,
    "Mourad Kochkar": 2.66,
    "Elyes Cyril Boughedir": 0.08,
    "Rania Ben Moussa": 9.93,
    "Mohamed Amine Neffati": 6.49,
    "Mohamed Amin Boukettaya": 0.02,
    "Mohamed Bettaieb Marouen": 6.49,
    "Nour Chouchane": 28.18
  },
  "Mehdi Bouthour": {
    "Seif Eddine Mezned": 20.34,
    "Mehdi Bouthour": 0.0,
    "Mahdi Soudani": 9.03,
    "Mimouna Baya Chaaben": 6.56,
    "Mohamed Aziz Souissi": 10.61,
    "Ahmed Said Mohamed": 2.96,
    "Aymen El Hadhri": 0.3,
    "Mohamed Yamoun Hamdi": 29.03,
    "Abdelkarim Elhamdi": 9.03,
    "Mohamed Amine Zekri": 18.61,
    "El Fedi Zairi": 16.61,
    "Aya Hachana": 16.96,
    "Abidi Fares": 8.61,
    "Mohamed Aymen Hassini": 23.03,
    "Arij Aouina": 5.96,
    "Yasmine Jedidi": 9.34,
    "Yasmine Ben Ismail": 26.56,
    "Emna Barbouch": 29.03,
    "Khammassi Nour": 0.0,
    "Youssef Mohamed Bechir": 104.0,
    "Ben Abda Iskander": 8.61,
    "Yassine Ben Knani": 104.0,
    "Nabila Ben Zineb": 0.35,
    "Mourad Kochkar": 0.35,
    "Elyes Cyril Boughedir": 9.34,
    "Rania Ben Moussa": 4.0,
    "Mohamed Amine Neffati": 6.96,
    "Mohamed Amin Boukettaya": 0.34,
    "Mohamed Bettaieb Marouen": 6.96,
    "Nour Chouchane": 18.61
  },
  "Mahdi Soudani": {
    "Seif Eddine Mezned": 7.19,
    "Mehdi Bouthour": 8.68,
    "Mahdi Soudani": 0.0,
    "Mimouna Baya Chaaben": 2.34,
    "Mohamed Aziz Souissi": 7.69,
    "Ahmed Said Mohamed": 3.23,
    "Aymen El Hadhri": 8.68,
    "Mohamed Yamoun Hamdi": 0.0,
    "Abdelkarim Elhamdi": 0.0,
    "Mohamed Amine Zekri": 7.69,
    "El Fedi Zairi": 7.69,
    "Aya Hachana": 6.01,
    "Abidi Fares": 7.69,
    "Mohamed Aymen Hassini": 0.0,
    "Arij Aouina": 3.23,
    "Yasmine Jedidi": 0.19,
    "Yasmine Ben Ismail": 2.34,
    "Emna Barbouch": 0.0,
    "Khammassi Nour": 8.68,
    "Youssef Mohamed Bechir": 9.45,
    "Ben Abda Iskander": 7.69,
    "Yassine Ben Knani": 9.45,
    "Nabila Ben Zineb": 2.17,
    "Mourad Kochkar": 2.17,
    "Elyes Cyril Boughedir": 0.19,
    "Rania Ben Moussa": 9.45,
    "Mohamed Amine Neffati": 6.01,
    "Mohamed Amin Boukettaya": 2.19,
    "Mohamed Bettaieb Marouen": 16.01,
    "Nour Chouchane": 7.69
  },
  "Mimouna Baya Chaaben": {
    "Seif Eddine Mezned": 13.62,
    "Mehdi Bouthour": 7.57,
    "Mahdi Soudani": 3.3,
    "Mimouna Baya Chaaben": 0.0,
    "Mohamed Aziz Souissi": 1.22,
    "Ahmed Said Mohamed": 0.24,
    "Aymen El Hadhri": 2.57,
    "Mohamed Yamoun Hamdi": 3.3,
    "Abdelkarim Elhamdi": 3.3,
    "Mohamed Amine Zekri": 1.52,
    "El Fedi Zairi": 1.22,
    "Aya Hachana": 1.23,
    "Abidi Fares": 1.22,
    "Mohamed Aymen Hassini": 3.3,
    "Arij Aouina": 0.24,
    "Yasmine Jedidi": 3.62,
    "Yasmine Ben Ismail": 0.0,
    "Emna Barbouch": 3.3,
    "Khammassi Nour": 7.57,
    "Youssef Mohamed Bechir": 2.77,
    "Ben Abda Iskander": 1.22,
    "Yassine Ben Knani": 2.77,
    "Nabila Ben Zineb": 1.83,
    "Mourad Kochkar": 1.83,
    "Elyes Cyril Boughedir": 3.62,
    "Rania Ben Moussa": 2.77,
    "Mohamed Amine Neffati": 1.23,
    "Mohamed Amin Boukettaya": 3.62,
    "Mohamed Bettaieb Marouen": 1.23,
    "Nour Chouchane": 11.22
  },
  "Mohamed Aziz Souissi": {
    "Seif Eddine Mezned": 28.15,
    "Mehdi Bouthour": 18.56,
    "Mahdi Soudani": 7.84,
    "Mimouna Baya Chaaben": 9.93,
    "Mohamed Aziz Souissi": 0.0,
    "Ahmed Said Mohamed": 4.77,
    "Aymen El Hadhri": 8.56,
    "Mohamed Yamoun Hamdi": 7.84,
    "Abdelkarim Elhamdi": 7.84,
    "Mohamed Amine Zekri": 0.0,
    "El Fedi Zairi": 0.0,
    "Aya Hachana": 5.77,
    "Abidi Fares": 0.0,
    "Mohamed Aymen Hassini": 7.84,
    "Arij Aouina": 4.77,
    "Yasmine Jedidi": 8.15,
    "Yasmine Ben Ismail": 9.93,
    "Emna Barbouch": 7.84,
    "Khammassi Nour": 8.56,
    "Youssef Mohamed Bechir": 2.81,
    "Ben Abda Iskander": 0.0,
    "Yassine Ben Knani": 2.81,
    "Nabila Ben Zineb": 6.37,
    "Mourad Kochkar": 6.37,
    "Elyes Cyril Boughedir": 8.15,
    "Rania Ben Moussa": 2.81,
    "Mohamed Amine Neffati": 25.77,
    "Mohamed Amin Boukettaya": 8.15,
    "Mohamed Bettaieb Marouen": 5.77,
    "Nour Chouchane": 0.2
  },
  "Ahmed Said Mohamed": {
    "Seif Eddine Mezned": 27.39,
    "Mehdi Bouthour": 5.88,
    "Mahdi Soudani": 5.86,
    "Mimouna Baya Chaaben": 9.53,
    "Mohamed Aziz Souissi": 4.89,
    "Ahmed Said Mohamed": 0.0,
    "Aymen El Hadhri": 5.88,
    "Mohamed Yamoun Hamdi": 2.86,
    "Abdelkarim Elhamdi": 2.86,
    "Mohamed Amine Zekri": 4.89,
    "El Fedi Zairi": 4.89,
    "Aya Hachana": 3.2,
    "Abidi Fares": 4.89,
    "Mohamed Aymen Hassini": 2.86,
    "Arij Aouina": 0.0,
    "Yasmine Jedidi": 7.39,
    "Yasmine Ben Ismail": 9.53,
    "Emna Barbouch": 2.86,
    "Khammassi Nour": 5.88,
    "Youssef Mohamed Bechir": 6.64,
    "Ben Abda Iskander": 4.89,
    "Yassine Ben Knani": 6.64,
    "Nabila Ben Zineb": 1.37,
    "Mourad Kochkar": 9.37,
    "Elyes Cyril Boughedir": 7.39,
    "Rania Ben Moussa": 6.64,
    "Mohamed Amine Neffati": 3.2,
    "Mohamed Amin Boukettaya": 2.39,
    "Mohamed Bettaieb Marouen": 3.2,
    "Nour Chouchane": 24.89
  },
  "Aymen El Hadhri": {
    "Seif Eddine Mezned": 29.34,
    "Mehdi Bouthour": 0.05,
    "Mahdi Soudani": 9.03,
    "Mimouna Baya Chaaben": 6.56,
    "Mohamed Aziz Souissi": 8.61,
    "Ahmed Said Mohamed": 5.96,
    "Aymen El Hadhri": 0.0,
    "Mohamed Yamoun Hamdi": 9.03,
    "Abdelkarim Elhamdi": 9.03,
    "Mohamed Amine Zekri": 8.61,
    "El Fedi Zairi": 8.61,
    "Aya Hachana": 6.96,
    "Abidi Fares": 8.61,
    "Mohamed Aymen Hassini": 9.03,
    "Arij Aouina": 5.96,
    "Yasmine Jedidi": 9.34,
    "Yasmine Ben Ismail": 6.56,
    "Emna Barbouch": 9.03,
    "Khammassi Nour": 0.0,
    "Youssef Mohamed Bechir": 4.0,
    "Ben Abda Iskander": 8.61,
    "Yassine Ben Knani": 4.0,
    "Nabila Ben Zineb": 0.35,
    "Mourad Kochkar": 0.35,
    "Elyes Cyril Boughedir": 9.34,
    "Rania Ben Moussa": 4.0,
    "Mohamed Amine Neffati": 6.96,
    "Mohamed Amin Boukettaya": 9.34,
    "Mohamed Bettaieb Marouen": 16.96,
    "Nour Chouchane": 18.61
  },
  "Mohamed Yamoun Hamdi": {
    "Seif Eddine Mezned": 7.19,
    "Mehdi Bouthour": 28.68,
    "Mahdi Soudani": 0.0,
    "Mimouna Baya Chaaben": 2.34,
    "Mohamed Aziz Souissi": 7.69,
    "Ahmed Said Mohamed": 3.23,
    "Aymen El Hadhri": 8.68,
    "Mohamed Yamoun Hamdi": 0.0,
    "Abdelkarim Elhamdi": 0.0,
    "Mohamed Amine Zekri": 7.69,
    "El Fedi Zairi": 7.69,
    "Aya Hachana": 6.01,
    "Abidi Fares": 7.69,
    "Mohamed Aymen Hassini": 0.0,
    "Arij Aouina": 3.23,
    "Yasmine Jedidi": 0.19,
    "Yasmine Ben Ismail": 2.34,
    "Emna Barbouch": 0.0,
    "Khammassi Nour": 8.68,
    "Youssef Mohamed Bechir": 9.45,
    "Ben Abda Iskander": 7.69,
    "Yassine Ben Knani": 9.45,
    "Nabila Ben Zineb": 2.17,
    "Mourad Kochkar": 2.17,
    "Elyes Cyril Boughedir": 0.19,
    "Rania Ben Moussa": 9.45,
    "Mohamed Amine Neffati": 6.01,
    "Mohamed Amin Boukettaya": 0.19,
    "Mohamed Bettaieb Marouen": 16.01,
    "Nour Chouchane": 7.69
  },
  "Abdelkarim Elhamdi": {
    "Seif Eddine Mezned": 5.19,
    "Mehdi Bouthour": 8.68,
    "Mahdi Soudani": 0.0,
    "Mimouna Baya Chaaben": 2.34,
    "Mohamed Aziz Souissi": 7.69,
    "Ahmed Said Mohamed": 3.23,
    "Aymen El Hadhri": 2.68,
    "Mohamed Yamoun Hamdi": 0.0,
    "Abdelkarim Elhamdi": 0.0,
    "Mohamed Amine Zekri": 7.69,
    "El Fedi Zairi": 7.69,
    "Aya Hachana": 6.01,
    "Abidi Fares": 3.69,
    "Mohamed Aymen Hassini": 0.0,
    "Arij Aouina": 3.23,
    "Yasmine Jedidi": 7.19,
    "Yasmine Ben Ismail": 2.34,
    "Emna Barbouch": 0.0,
    "Khammassi Nour": 8.68,
    "Youssef Mohamed Bechir": 9.45,
    "Ben Abda Iskander": 0.12,
    "Yassine Ben Knani": 9.45,
    "Nabila Ben Zineb": 2.17,
    "Mourad Kochkar": 2.17,
    "Elyes Cyril Boughedir": 0.19,
    "Rania Ben Moussa": 9.45,
    "Mohamed Amine Neffati": 6.01,
    "Mohamed Amin Boukettaya": 7.19,
    "Mohamed Bettaieb Marouen": 6.01,
    "Nour Chouchane": 7.69
  },
  "Mohamed Amine Zekri": {
    "Seif Eddine Mezned": 2.15,
    "Mehdi Bouthour": 8.56,
    "Mahdi Soudani": 7.84,
    "Mimouna Baya Chaaben": 0.93,
    "Mohamed Aziz Souissi": 0.0,
    "Ahmed Said Mohamed": 4.77,
    "Aymen El Hadhri": 8.56,
    "Mohamed Yamoun Hamdi": 7.84,
    "Abdelkarim Elhamdi": 7.84,
    "Mohamed Amine Zekri": 0.0,
    "El Fedi Zairi": 0.0,
    "Aya Hachana": 5.77,
    "Abidi Fares": 0.0,
    "Mohamed Aymen Hassini": 7.84,
    "Arij Aouina": 4.77,
    "Yasmine Jedidi": 8.15,
    "Yasmine Ben Ismail": 9.93,
    "Emna Barbouch": 7.84,
    "Khammassi Nour": 8.56,
    "Youssef Mohamed Bechir": 2.81,
    "Ben Abda Iskander": 0.0,
    "Yassine Ben Knani": 2.81,
    "Nabila Ben Zineb": 1.37,
    "Mourad Kochkar": 6.37,
    "Elyes Cyril Boughedir": 8.15,
    "Rania Ben Moussa": 2.81,
    "Mohamed Amine Neffati": 25.77,
    "Mohamed Amin Boukettaya": 8.15,
    "Mohamed Bettaieb Marouen": 25.77,
    "Nour Chouchane": 0.67
  },
  "El Fedi Zairi": {
    "Seif Eddine Mezned": 26.15,
    "Mehdi Bouthour": 18.56,
    "Mahdi Soudani": 7.84,
    "Mimouna Baya Chaaben": 9.93,
    "Mohamed Aziz Souissi": 0.0,
    "Ahmed Said Mohamed": 4.77,
    "Aymen El Hadhri": 8.56,
    "Mohamed Yamoun Hamdi": 7.84,
    "Abdelkarim Elhamdi": 7.84,
    "Mohamed Amine Zekri": 0.0,
    "El Fedi Zairi": 0.0,
    "Aya Hachana": 5.77,
    "Abidi Fares": 0.0,
    "Mohamed Aymen Hassini": 7.84,
    "Arij Aouina": 4.77,
    "Yasmine Jedidi": 8.15,
    "Yasmine Ben Ismail": 9.93,
    "Emna Barbouch": 7.84,
    "Khammassi Nour": 8.56,
    "Youssef Mohamed Bechir": 2.81,
    "Ben Abda Iskander": 0.0,
    "Yassine Ben Knani": 2.81,
    "Nabila Ben Zineb": 6.37,
    "Mourad Kochkar": 6.37,
    "Elyes Cyril Boughedir": 8.15,
    "Rania Ben Moussa": 0.81,
    "Mohamed Amine Neffati": 5.77,
    "Mohamed Amin Boukettaya": 8.15,
    "Mohamed Bettaieb Marouen": 25.77,
    "Nour Chouchane": 0.3
  },
  "Aya Hachana": {
    "Seif Eddine Mezned": 6.64,
    "Mehdi Bouthour": 6.28,
    "Mahdi Soudani": 6.33,
    "Mimouna Baya Chaaben": 9.94,
    "Mohamed Aziz Souissi": 5.29,
    "Ahmed Said Mohamed": 9.26,
    "Aymen El Hadhri": 6.28,
    "Mohamed Yamoun Hamdi": 6.33,
    "Abdelkarim Elhamdi": 6.33,
    "Mohamed Amine Zekri": 5.29,
    "El Fedi Zairi": 5.29,
    "Aya Hachana": 0.0,
    "Abidi Fares": 5.29,
    "Mohamed Aymen Hassini": 6.33,
    "Arij Aouina": 3.26,
    "Yasmine Jedidi": 6.64,
    "Yasmine Ben Ismail": 9.94,
    "Emna Barbouch": 6.33,
    "Khammassi Nour": 6.28,
    "Youssef Mohamed Bechir": 7.04,
    "Ben Abda Iskander": 5.29,
    "Yassine Ben Knani": 7.04,
    "Nabila Ben Zineb": 9.77,
    "Mourad Kochkar": 9.77,
    "Elyes Cyril Boughedir": 6.64,
    "Rania Ben Moussa": 7.04,
    "Mohamed Amine Neffati": 0.2,
    "Mohamed Amin Boukettaya": 6.64,
    "Mohamed Bettaieb Marouen": 0.0,
    "Nour Chouchane": 25.29
  },
  "Abidi Fares": {
    "Seif Eddine Mezned": 8.15,
    "Mehdi Bouthour": 1.56,
    "Mahdi Soudani": 7.84,
    "Mimouna Baya Chaaben": 9.93,
    "Mohamed Aziz Souissi": 0.0,
    "Ahmed Said Mohamed": 4.77,
    "Aymen El Hadhri": 8.56,
    "Mohamed Yamoun Hamdi": 7.84,
    "Abdelkarim Elhamdi": 7.84,
    "Mohamed Amine Zekri": 0.0,
    "El Fedi Zairi": 0.0,
    "Aya Hachana": 5.77,
    "Abidi Fares": 0.0,
    "Mohamed Aymen Hassini": 7.84,
    "Arij Aouina": 4.77,
    "Yasmine Jedidi": 2.15,
    "Yasmine Ben Ismail": 1.93,
    "Emna Barbouch": 3.84,
    "Khammassi Nour": 8.56,
    "Youssef Mohamed Bechir": 2.81,
    "Ben Abda Iskander": 0.0,
    "Yassine Ben Knani": 2.81,
    "Nabila Ben Zineb": 6.37,
    "Mourad Kochkar": 3.37,
    "Elyes Cyril Boughedir": 8.15,
    "Rania Ben Moussa": 2.81,
    "Mohamed Amine Neffati": 5.77,
    "Mohamed Amin Boukettaya": 8.15,
    "Mohamed Bettaieb Marouen": 5.77,
    "Nour Chouchane": 0.2
  },
  "Mohamed Aymen Hassini": {
    "Seif Eddine Mezned": 1.19,
    "Mehdi Bouthour": 8.68,
    "Mahdi Soudani": 0.02,
    "Mimouna Baya Chaaben": 2.34,
    "Mohamed Aziz Souissi": 7.69,
    "Ahmed Said Mohamed": 3.23,
    "Aymen El Hadhri": 8.68,
    "Mohamed Yamoun Hamdi": 0.0,
    "Abdelkarim Elhamdi": 0.0,
    "Mohamed Amine Zekri": 7.69,
    "El Fedi Zairi": 7.69,
    "Aya Hachana": 6.01,
    "Abidi Fares": 7.69,
    "Mohamed Aymen Hassini": 0.0,
    "Arij Aouina": 3.23,
    "Yasmine Jedidi": 0.19,
    "Yasmine Ben Ismail": 2.34,
    "Emna Barbouch": 0.0,
    "Khammassi Nour": 8.68,
    "Youssef Mohamed Bechir": 9.45,
    "Ben Abda Iskander": 7.69,
    "Yassine Ben Knani": 9.45,
    "Nabila Ben Zineb": 2.17,
    "Mourad Kochkar": 2.17,
    "Elyes Cyril Boughedir": 0.19,
    "Rania Ben Moussa": 9.45,
    "Mohamed Amine Neffati": 6.01,
    "Mohamed Amin Boukettaya": 0.19,
    "Mohamed Bettaieb Marouen": 6.01,
    "Nour Chouchane": 7.69
  },
  "Arij Aouina": {
    "Seif Eddine Mezned": 2.39,
    "Mehdi Bouthour": 5.88,
    "Mahdi Soudani": 2.86,
    "Mimouna Baya Chaaben": 9.53,
    "Mohamed Aziz Souissi": 4.89,
    "Ahmed Said Mohamed": 0.0,
    "Aymen El Hadhri": 5.88,
    "Mohamed Yamoun Hamdi": 2.86,
    "Abdelkarim Elhamdi": 5.86,
    "Mohamed Amine Zekri": 4.89,
    "El Fedi Zairi": 4.89,
    "Aya Hachana": 3.2,
    "Abidi Fares": 4.89,
    "Mohamed Aymen Hassini": 5.86,
    "Arij Aouina": 0.0,
    "Yasmine Jedidi": 27.39,
    "Yasmine Ben Ismail": 9.53,
    "Emna Barbouch": 2.86,
    "Khammassi Nour": 5.88,
    "Youssef Mohamed Bechir": 6.64,
    "Ben Abda Iskander": 2.89,
    "Yassine Ben Knani": 6.64,
    "Nabila Ben Zineb": 1.37,
    "Mourad Kochkar": 1.37,
    "Elyes Cyril Boughedir": 27.39,
    "Rania Ben Moussa": 2.64,
    "Mohamed Amine Neffati": 3.2,
    "Mohamed Amin Boukettaya": 7.39,
    "Mohamed Bettaieb Marouen": 3.2,
    "Nour Chouchane": 4.89
  },
  "Yasmine Jedidi": {
    "Seif Eddine Mezned": 0.03,
    "Mehdi Bouthour": 29.17,
    "Mahdi Soudani": 0.19,
    "Mimouna Baya Chaaben": 2.82,
    "Mohamed Aziz Souissi": 8.18,
    "Ahmed Said Mohamed": 7.12,
    "Aymen El Hadhri": 9.17,
    "Mohamed Yamoun Hamdi": 0.19,
    "Abdelkarim Elhamdi": 0.19,
    "Mohamed Amine Zekri": 8.18,
    "El Fedi Zairi": 8.18,
    "Aya Hachana": 6.49,
    "Abidi Fares": 8.18,
    "Mohamed Aymen Hassini": 0.19,
    "Arij Aouina": 7.12,
    "Yasmine Jedidi": 0.0,
    "Yasmine Ben Ismail": 2.82,
    "Emna Barbouch": 0.19,
    "Khammassi Nour": 9.17,
    "Youssef Mohamed Bechir": 9.93,
    "Ben Abda Iskander": 8.18,
    "Yassine Ben Knani": 9.93,
    "Nabila Ben Zineb": 2.66,
    "Mourad Kochkar": 2.66,
    "Elyes Cyril Boughedir": 0.0,
    "Rania Ben Moussa": 9.93,
    "Mohamed Amine Neffati": 6.49,
    "Mohamed Amin Boukettaya": 1.4,
    "Mohamed Bettaieb Marouen": 6.49,
    "Nour Chouchane": 8.18
  },
  "Yasmine Ben Ismail": {
    "Seif Eddine Mezned": 3.62,
    "Mehdi Bouthour": 7.57,
    "Mahdi Soudani": 3.3,
    "Mimouna Baya Chaaben": 0.0,
    "Mohamed Aziz Souissi": 1.22,
    "Ahmed Said Mohamed": 0.24,
    "Aymen El Hadhri": 7.57,
    "Mohamed Yamoun Hamdi": 3.3,
    "Abdelkarim Elhamdi": 3.3,
    "Mohamed Amine Zekri": 1.22,
    "El Fedi Zairi": 1.22,
    "Aya Hachana": 1.23,
    "Abidi Fares": 1.22,
    "Mohamed Aymen Hassini": 3.3,
    "Arij Aouina": 0.24,
    "Yasmine Jedidi": 3.62,
    "Yasmine Ben Ismail": 0.0,
    "Emna Barbouch": 0.3,
    "Khammassi Nour": 7.57,
    "Youssef Mohamed Bechir": 2.77,
    "Ben Abda Iskander": 1.22,
    "Yassine Ben Knani": 2.77,
    "Nabila Ben Zineb": 1.83,
    "Mourad Kochkar": 1.83,
    "Elyes Cyril Boughedir": 4.62,
    "Rania Ben Moussa": 2.77,
    "Mohamed Amine Neffati": 1.23,
    "Mohamed Amin Boukettaya": 3.62,
    "Mohamed Bettaieb Marouen": 1.23,
    "Nour Chouchane": 1.22
  },
  "Emna Barbouch": {
    "Seif Eddine Mezned": 7.19,
    "Mehdi Bouthour": 8.68,
    "Mahdi Soudani": 0.2,
    "Mimouna Baya Chaaben": 2.34,
    "Mohamed Aziz Souissi": 7.69,
    "Ahmed Said Mohamed": 3.23,
    "Aymen El Hadhri": 8.68,
    "Mohamed Yamoun Hamdi": 0.0,
    "Abdelkarim Elhamdi": 0.0,
    "Mohamed Amine Zekri": 7.69,
    "El Fedi Zairi": 7.69,
    "Aya Hachana": 6.01,
    "Abidi Fares": 7.69,
    "Mohamed Aymen Hassini": 0.0,
    "Arij Aouina": 3.23,
    "Yasmine Jedidi": 0.19,
    "Yasmine Ben Ismail": 2.34,
    "Emna Barbouch": 0.0,
    "Khammassi Nour": 8.68,
    "Youssef Mohamed Bechir": 9.45,
    "Ben Abda Iskander": 7.69,
    "Yassine Ben Knani": 9.45,
    "Nabila Ben Zineb": 2.17,
    "Mourad Kochkar": 2.17,
    "Elyes Cyril Boughedir": 7.19,
    "Rania Ben Moussa": 0.2,
    "Mohamed Amine Neffati": 6.01,
    "Mohamed Amin Boukettaya": 0.19,
    "Mohamed Bettaieb Marouen": 16.01,
    "Nour Chouchane": 7.69
  },
  "Khammassi Nour": {
    "Seif Eddine Mezned": 9.34,
    "Mehdi Bouthour": 0.5,
    "Mahdi Soudani": 9.03,
    "Mimouna Baya Chaaben": 6.56,
    "Mohamed Aziz Souissi": 8.61,
    "Ahmed Said Mohamed": 5.96,
    "Aymen El Hadhri": 0.0,
    "Mohamed Yamoun Hamdi": 9.03,
    "Abdelkarim Elhamdi": 9.03,
    "Mohamed Amine Zekri": 8.61,
    "El Fedi Zairi": 8.61,
    "Aya Hachana": 1.96,
    "Abidi Fares": 8.61,
    "Mohamed Aymen Hassini": 9.03,
    "Arij Aouina": 5.96,
    "Yasmine Jedidi": 9.34,
    "Yasmine Ben Ismail": 6.56,
    "Emna Barbouch": 9.03,
    "Khammassi Nour": 0.0,
    "Youssef Mohamed Bechir": 10.4,
    "Ben Abda Iskander": 8.61,
    "Yassine Ben Knani": 4.0,
    "Nabila Ben Zineb": 0.35,
    "Mourad Kochkar": 0.35,
    "Elyes Cyril Boughedir": 9.34,
    "Rania Ben Moussa": 4.0,
    "Mohamed Amine Neffati": 6.96,
    "Mohamed Amin Boukettaya": 9.34,
    "Mohamed Bettaieb Marouen": 6.96,
    "Nour Chouchane": 18.61
  },
  "Youssef Mohamed Bechir": {
    "Seif Eddine Mezned": 1.48,
    "Mehdi Bouthour": 13.56,
    "Mahdi Soudani": 8.17,
    "Mimouna Baya Chaaben": 1.34,
    "Mohamed Aziz Souissi": 6.46,
    "Ahmed Said Mohamed": 5.1,
    "Aymen El Hadhri": 3.56,
    "Mohamed Yamoun Hamdi": 8.17,
    "Abdelkarim Elhamdi": 8.17,
    "Mohamed Amine Zekri": 6.46,
    "El Fedi Zairi": 6.46,
    "Aya Hachana": 6.1,
    "Abidi Fares": 6.46,
    "Mohamed Aymen Hassini": 8.17,
    "Arij Aouina": 5.1,
    "Yasmine Jedidi": 8.48,
    "Yasmine Ben Ismail": 1.34,
    "Emna Barbouch": 8.17,
    "Khammassi Nour": 3.56,
    "Youssef Mohamed Bechir": 0.0,
    "Ben Abda Iskander": 6.46,
    "Yassine Ben Knani": 0.0,
    "Nabila Ben Zineb": 6.15,
    "Mourad Kochkar": 6.15,
    "Elyes Cyril Boughedir": 8.48,
    "Rania Ben Moussa": 0.0,
    "Mohamed Amine Neffati": 6.1,
    "Mohamed Amin Boukettaya": 8.48,
    "Mohamed Bettaieb Marouen": 16.1,
    "Nour Chouchane": 16.46
  },
  "Ben Abda Iskander": {
    "Seif Eddine Mezned": 8.15,
    "Mehdi Bouthour": 18.56,
    "Mahdi Soudani": 7.84,
    "Mimouna Baya Chaaben": 9.93,
    "Mohamed Aziz Souissi": 0.0,
    "Ahmed Said Mohamed": 4.77,
    "Aymen El Hadhri": 8.56,
    "Mohamed Yamoun Hamdi": 7.84,
    "Abdelkarim Elhamdi": 7.84,
    "Mohamed Amine Zekri": 0.0,
    "El Fedi Zairi": 0.0,
    "Aya Hachana": 5.77,
    "Abidi Fares": 0.0,
    "Mohamed Aymen Hassini": 7.84,
    "Arij Aouina": 2.77,
    "Yasmine Jedidi": 8.15,
    "Yasmine Ben Ismail": 9.93,
    "Emna Barbouch": 7.84,
    "Khammassi Nour": 8.56,
    "Youssef Mohamed Bechir": 2.81,
    "Ben Abda Iskander": 0.0,
    "Yassine Ben Knani": 2.81,
    "Nabila Ben Zineb": 6.37,
    "Mourad Kochkar": 6.37,
    "Elyes Cyril Boughedir": 8.15,
    "Rania Ben Moussa": 2.81,
    "Mohamed Amine Neffati": 5.77,
    "Mohamed Amin Boukettaya": 8.15,
    "Mohamed Bettaieb Marouen": 25.77,
    "Nour Chouchane": 0.2
  },
  "Yassine Ben Knani": {
    "Seif Eddine Mezned": 18.48,
    "Mehdi Bouthour": 3.56,
    "Mahdi Soudani": 8.17,
    "Mimouna Baya Chaaben": 1.34,
    "Mohamed Aziz Souissi": 6.46,
    "Ahmed Said Mohamed": 5.1,
    "Aymen El Hadhri": 3.56,
    "Mohamed Yamoun Hamdi": 8.17,
    "Abdelkarim Elhamdi": 8.17,
    "Mohamed Amine Zekri": 6.46,
    "El Fedi Zairi": 6.46,
    "Aya Hachana": 6.1,
    "Abidi Fares": 6.46,
    "Mohamed Aymen Hassini": 8.17,
    "Arij Aouina": 215.1,
    "Yasmine Jedidi": 8.48,
    "Yasmine Ben Ismail": 1.34,
    "Emna Barbouch": 8.17,
    "Khammassi Nour": 3.56,
    "Youssef Mohamed Bechir": 0.0,
    "Ben Abda Iskander": 6.46,
    "Yassine Ben Knani": 0.0,
    "Nabila Ben Zineb": 16.15,
    "Mourad Kochkar": 6.15,
    "Elyes Cyril Boughedir": 8.48,
    "Rania Ben Moussa": 0.0,
    "Mohamed Amine Neffati": 6.1,
    "Mohamed Amin Boukettaya": 8.48,
    "Mohamed Bettaieb Marouen": 6.1,
    "Nour Chouchane": 16.46
  },
  "Nabila Ben Zineb": {
    "Seif Eddine Mezned": 4.19,
    "Mehdi Bouthour": 2.02,
    "Mahdi Soudani": 0.88,
    "Mimouna Baya Chaaben": 0.88,
    "Mohamed Aziz Souissi": 6.24,
    "Ahmed Said Mohamed": 3.81,
    "Aymen El Hadhri": 2.02,
    "Mohamed Yamoun Hamdi": 6.88,
    "Abdelkarim Elhamdi": 6.88,
    "Mohamed Amine Zekri": 6.24,
    "El Fedi Zairi": 6.24,
    "Aya Hachana": 4.81,
    "Abidi Fares": 6.24,
    "Mohamed Aymen Hassini": 6.88,
    "Arij Aouina": 3.81,
    "Yasmine Jedidi": 7.19,
    "Yasmine Ben Ismail": 0.88,
    "Emna Barbouch": 6.88,
    "Khammassi Nour": 6.02,
    "Youssef Mohamed Bechir": 0.07,
    "Ben Abda Iskander": 6.24,
    "Yassine Ben Knani": 7.07,
    "Nabila Ben Zineb": 0.0,
    "Mourad Kochkar": 0.0,
    "Elyes Cyril Boughedir": 7.19,
    "Rania Ben Moussa": 7.07,
    "Mohamed Amine Neffati": 14.81,
    "Mohamed Amin Boukettaya": 7.19,
    "Mohamed Bettaieb Marouen": 4.81,
    "Nour Chouchane": 16.24
  },
  "Mourad Kochkar": {
    "Seif Eddine Mezned": 7.19,
    "Mehdi Bouthour": 12.02,
    "Mahdi Soudani": 6.88,
    "Mimouna Baya Chaaben": 0.88,
    "Mohamed Aziz Souissi": 6.24,
    "Ahmed Said Mohamed": 3.81,
    "Aymen El Hadhri": 2.02,
    "Mohamed Yamoun Hamdi": 6.88,
    "Abdelkarim Elhamdi": 6.88,
    "Mohamed Amine Zekri": 6.24,
    "El Fedi Zairi": 1.24,
    "Aya Hachana": 1.81,
    "Abidi Fares": 6.24,
    "Mohamed Aymen Hassini": 2.88,
    "Arij Aouina": 3.81,
    "Yasmine Jedidi": 7.19,
    "Yasmine Ben Ismail": 0.88,
    "Emna Barbouch": 6.88,
    "Khammassi Nour": 2.02,
    "Youssef Mohamed Bechir": 7.07,
    "Ben Abda Iskander": 6.24,
    "Yassine Ben Knani": 7.07,
    "Nabila Ben Zineb": 0.0,
    "Mourad Kochkar": 0.0,
    "Elyes Cyril Boughedir": 7.19,
    "Rania Ben Moussa": 7.07,
    "Mohamed Amine Neffati": 4.81,
    "Mohamed Amin Boukettaya": 7.19,
    "Mohamed Bettaieb Marouen": 1.81,
    "Nour Chouchane": 6.24
  },
  "Elyes Cyril Boughedir": {
    "Seif Eddine Mezned": 5.6,
    "Mehdi Bouthour": 9.17,
    "Mahdi Soudani": 7.19,
    "Mimouna Baya Chaaben": 12.82,
    "Mohamed Aziz Souissi": 8.18,
    "Ahmed Said Mohamed": 7.12,
    "Aymen El Hadhri": 9.17,
    "Mohamed Yamoun Hamdi": 7.19,
    "Abdelkarim Elhamdi": 7.19,
    "Mohamed Amine Zekri": 8.18,
    "El Fedi Zairi": 8.18,
    "Aya Hachana": 6.49,
    "Abidi Fares": 8.18,
    "Mohamed Aymen Hassini": 0.19,
    "Arij Aouina": 7.12,
    "Yasmine Jedidi": 0.0,
    "Yasmine Ben Ismail": 2.82,
    "Emna Barbouch": 0.19,
    "Khammassi Nour": 9.17,
    "Youssef Mohamed Bechir": 9.93,
    "Ben Abda Iskander": 8.18,
    "Yassine Ben Knani": 9.93,
    "Nabila Ben Zineb": 1.66,
    "Mourad Kochkar": 2.66,
    "Elyes Cyril Boughedir": 0.0,
    "Rania Ben Moussa": 9.93,
    "Mohamed Amine Neffati": 6.49,
    "Mohamed Amin Boukettaya": 0.0,
    "Mohamed Bettaieb Marouen": 6.49,
    "Nour Chouchane": 8.18
  },
  "Rania Ben Moussa": {
    "Seif Eddine Mezned": 1.48,
    "Mehdi Bouthour": 3.56,
    "Mahdi Soudani": 8.17,
    "Mimouna Baya Chaaben": 1.34,
    "Mohamed Aziz Souissi": 6.46,
    "Ahmed Said Mohamed": 2.1,
    "Aymen El Hadhri": 10.56,
    "Mohamed Yamoun Hamdi": 8.17,
    "Abdelkarim Elhamdi": 2.17,
    "Mohamed Amine Zekri": 1.46,
    "El Fedi Zairi": 1.46,
    "Aya Hachana": 6.1,
    "Abidi Fares": 6.46,
    "Mohamed Aymen Hassini": 8.17,
    "Arij Aouina": 5.1,
    "Yasmine Jedidi": 8.48,
    "Yasmine Ben Ismail": 1.34,
    "Emna Barbouch": 8.17,
    "Khammassi Nour": 3.56,
    "Youssef Mohamed Bechir": 0.0,
    "Ben Abda Iskander": 6.46,
    "Yassine Ben Knani": 0.0,
    "Nabila Ben Zineb": 6.15,
    "Mourad Kochkar": 0.15,
    "Elyes Cyril Boughedir": 8.48,
    "Rania Ben Moussa": 0.0,
    "Mohamed Amine Neffati": 6.1,
    "Mohamed Amin Boukettaya": 8.48,
    "Mohamed Bettaieb Marouen": 6.1,
    "Nour Chouchane": 6.46
  },
  "Mohamed Amine Neffati": {
    "Seif Eddine Mezned": 6.64,
    "Mehdi Bouthour": 16.28,
    "Mahdi Soudani": 16.33,
    "Mimouna Baya Chaaben": 9.94,
    "Mohamed Aziz Souissi": 5.29,
    "Ahmed Said Mohamed": 3.26,
    "Aymen El Hadhri": 6.28,
    "Mohamed Yamoun Hamdi": 6.33,
    "Abdelkarim Elhamdi": 1.33,
    "Mohamed Amine Zekri": 2.29,
    "El Fedi Zairi": 5.29,
    "Aya Hachana": 0.0,
    "Abidi Fares": 5.29,
    "Mohamed Aymen Hassini": 6.33,
    "Arij Aouina": 3.26,
    "Yasmine Jedidi": 6.64,
    "Yasmine Ben Ismail": 9.94,
    "Emna Barbouch": 6.33,
    "Khammassi Nour": 6.28,
    "Youssef Mohamed Bechir": 7.04,
    "Ben Abda Iskander": 5.29,
    "Yassine Ben Knani": 7.04,
    "Nabila Ben Zineb": 9.77,
    "Mourad Kochkar": 9.77,
    "Elyes Cyril Boughedir": 6.64,
    "Rania Ben Moussa": 7.04,
    "Mohamed Amine Neffati": 0.0,
    "Mohamed Amin Boukettaya": 6.64,
    "Mohamed Bettaieb Marouen": 0.2,
    "Nour Chouchane": 5.29
  },
  "Mohamed Amin Boukettaya": {
    "Seif Eddine Mezned": 0.0,
    "Mehdi Bouthour": 9.17,
    "Mahdi Soudani": 0.19,
    "Mimouna Baya Chaaben": 2.82,
    "Mohamed Aziz Souissi": 8.18,
    "Ahmed Said Mohamed": 7.12,
    "Aymen El Hadhri": 9.17,
    "Mohamed Yamoun Hamdi": 0.19,
    "Abdelkarim Elhamdi": 0.19,
    "Mohamed Amine Zekri": 8.18,
    "El Fedi Zairi": 8.18,
    "Aya Hachana": 6.49,
    "Abidi Fares": 8.18,
    "Mohamed Aymen Hassini": 0.19,
    "Arij Aouina": 7.12,
    "Yasmine Jedidi": 0.0,
    "Yasmine Ben Ismail": 2.82,
    "Emna Barbouch": 0.19,
    "Khammassi Nour": 9.17,
    "Youssef Mohamed Bechir": 9.93,
    "Ben Abda Iskander": 8.18,
    "Yassine Ben Knani": 9.93,
    "Nabila Ben Zineb": 2.66,
    "Mourad Kochkar": 2.66,
    "Elyes Cyril Boughedir": 0.2,
    "Rania Ben Moussa": 9.93,
    "Mohamed Amine Neffati": 6.49,
    "Mohamed Amin Boukettaya": 0.0,
    "Mohamed Bettaieb Marouen": 6.49,
    "Nour Chouchane": 8.18
  },
  "Mohamed Bettaieb Marouen": {
    "Seif Eddine Mezned": 6.64,
    "Mehdi Bouthour": 6.28,
    "Mahdi Soudani": 16.33,
    "Mimouna Baya Chaaben": 9.94,
    "Mohamed Aziz Souissi": 5.29,
    "Ahmed Said Mohamed": 3.26,
    "Aymen El Hadhri": 6.28,
    "Mohamed Yamoun Hamdi": 6.33,
    "Abdelkarim Elhamdi": 1.33,
    "Mohamed Amine Zekri": 5.29,
    "El Fedi Zairi": 5.29,
    "Aya Hachana": 0.0,
    "Abidi Fares": 5.29,
    "Mohamed Aymen Hassini": 16.33,
    "Arij Aouina": 3.26,
    "Yasmine Jedidi": 6.64,
    "Yasmine Ben Ismail": 9.94,
    "Emna Barbouch": 1.33,
    "Khammassi Nour": 6.28,
    "Youssef Mohamed Bechir": 7.04,
    "Ben Abda Iskander": 5.29,
    "Yassine Ben Knani": 7.04,
    "Nabila Ben Zineb": 9.77,
    "Mourad Kochkar": 9.77,
    "Elyes Cyril Boughedir": 6.64,
    "Rania Ben Moussa": 7.04,
    "Mohamed Amine Neffati": 0.0,
    "Mohamed Amin Boukettaya": 6.64,
    "Mohamed Bettaieb Marouen": 0.0,
    "Nour Chouchane": 5.29
  },
  "Nour Chouchane": {
    "Seif Eddine Mezned": 8.15,
    "Mehdi Bouthour": 18.56,
    "Mahdi Soudani": 7.84,
    "Mimouna Baya Chaaben": 19.93,
    "Mohamed Aziz Souissi": 0.0,
    "Ahmed Said Mohamed": 4.77,
    "Aymen El Hadhri": 18.56,
    "Mohamed Yamoun Hamdi": 7.84,
    "Abdelkarim Elhamdi": 7.84,
    "Mohamed Amine Zekri": 0.0,
    "El Fedi Zairi": 0.0,
    "Aya Hachana": 5.77,
    "Abidi Fares": 0.0,
    "Mohamed Aymen Hassini": 7.84,
    "Arij Aouina": 4.77,
    "Yasmine Jedidi": 2.15,
    "Yasmine Ben Ismail": 9.93,
    "Emna Barbouch": 7.84,
    "Khammassi Nour": 0.56,
    "Youssef Mohamed Bechir": 2.81,
    "Ben Abda Iskander": 0.0,
    "Yassine Ben Knani": 2.81,
    "Nabila Ben Zineb": 6.37,
    "Mourad Kochkar": 6.37,
    "Elyes Cyril Boughedir": 8.15,
    "Rania Ben Moussa": 2.81,
    "Mohamed Amine Neffati": 5.77,
    "Mohamed Amin Boukettaya": 8.15,
    "Mohamed Bettaieb Marouen": 5.77,
    "Nour Chouchane": 0.0
  }
}

students = list(distance_dict.keys())

# Build graph
def create_graph(dist_dict):
  G = nx.Graph()
  for i in dist_dict:
    for j in dist_dict[i]:
      if i != j:
        G.add_edge(i, j, weight=dist_dict[i][j])
  return G

G = create_graph(distance_dict)

# Session state
if 'role' not in st.session_state:
  st.session_state.role = None
if 'requests' not in st.session_state:
  st.session_state.requests = {}
if 'accepted' not in st.session_state:
  st.session_state.accepted = {}

st.title("🚗 SMU Carpooling Network App")

current_user = st.selectbox("Select your name:", students)

if st.session_state.role is None:
  st.session_state.role = st.radio("Are you a driver or a passenger?", ["Driver", "Passenger"])

random.seed(42)
drivers = random.sample([s for s in students if s != current_user], min(7, len(students) - 1))

st.markdown("### 👥 Carpool Network Graph (All Students)")
fig1, ax1 = plt.subplots(figsize=(10, 8))
pos = nx.spring_layout(G, seed=42)
nx.draw(G, pos, with_labels=True, node_size=500, font_size=8, ax=ax1)
st.pyplot(fig1)

# Passenger
if st.session_state.role == "Passenger":
  available_drivers = [d for d in drivers if d != current_user]
  selected_driver = st.selectbox("Select a driver to request carpool with:", available_drivers)
  if st.button("Send Request"):
    st.session_state.requests.setdefault(selected_driver, []).append(current_user)
    st.success(f"Request sent to {selected_driver}")

# Driver
if st.session_state.role == "Driver":
  st.markdown(f"### 🚘 Welcome Driver: **{current_user}**")
  requests = st.session_state.requests.get(current_user, [])
  if requests:
    for passenger in requests:
      col1, col2 = st.columns([2, 1])
      with col1:
        st.write(f"Passenger request from: {passenger}")
      with col2:
        if st.button(f"Accept {passenger}"):
          st.session_state.accepted.setdefault(current_user, []).append(passenger)
          st.success(f"Accepted {passenger}")
  else:
    st.info("No requests yet.")

# Shortest path graph
if st.session_state.role == "Driver" and current_user in st.session_state.accepted:
  passengers = st.session_state.accepted[current_user]
  st.markdown("### 🗺️ Shortest Path Graph to Passengers")
  fig2, ax2 = plt.subplots(figsize=(10, 8))
  shortest_path_graph = nx.Graph()
  for p in passengers:
    try:
      path = nx.shortest_path(G, source=current_user, target=p, weight='weight')
      nx.add_path(shortest_path_graph, path)
    except nx.NetworkXNoPath:
      st.warning(f"No path between {current_user} and {p}")
  nx.draw(shortest_path_graph, pos, with_labels=True, node_size=500, font_size=8, ax=ax2, edge_color='green')
  st.pyplot(fig2)

st.markdown("---")
st.caption("SMU Carpooling App using Graph Theory | All data embedded")

